package com.satimetry.nudge;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FastDiet implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "User ID")
   private int userid;
   @org.kie.api.definition.type.Label(value = "Fast Count")
   private int fastcount;
   @org.kie.api.definition.type.Label(value = "Exercise Count")
   private int exercisecount;

   public FastDiet()
   {
   }

   public int getUserid()
   {
      return this.userid;
   }

   public void setUserid(int userid)
   {
      this.userid = userid;
   }

   public int getFastcount()
   {
      return this.fastcount;
   }

   public void setFastcount(int fastcount)
   {
      this.fastcount = fastcount;
   }

   public int getExercisecount()
   {
      return this.exercisecount;
   }

   public void setExercisecount(int exercisecount)
   {
      this.exercisecount = exercisecount;
   }

   public FastDiet(int userid, int fastcount, int exercisecount)
   {
      this.userid = userid;
      this.fastcount = fastcount;
      this.exercisecount = exercisecount;
   }

}