package com.satimetry.nudge;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Msg implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "User ID")
   private int userid;
   @org.kie.api.definition.type.Label(value = "Msg Txt")
   private java.lang.String msgtxt;

   public Msg()
   {
   }

   public int getUserid()
   {
      return this.userid;
   }

   public void setUserid(int userid)
   {
      this.userid = userid;
   }

   public java.lang.String getMsgtxt()
   {
      return this.msgtxt;
   }

   public void setMsgtxt(java.lang.String msgtxt)
   {
      this.msgtxt = msgtxt;
   }

   public Msg(int userid, java.lang.String msgtxt)
   {
      this.userid = userid;
      this.msgtxt = msgtxt;
   }

}