package com.satimetry.nudge;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Role(org.kie.api.definition.type.Role.Type.EVENT)
@org.kie.api.definition.type.Timestamp("obsdate")
public class Observation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "User ID")
   private int userid;
   @org.kie.api.definition.type.Label(value = "Obs Date")
   private java.util.Date obsdate;
   @org.kie.api.definition.type.Label(value = "Obs Value")
   private int obsvalue;

   public Observation()
   {
   }

   public int getUserid()
   {
      return this.userid;
   }

   public void setUserid(int userid)
   {
      this.userid = userid;
   }

   public java.util.Date getObsdate()
   {
      return this.obsdate;
   }

   public void setObsdate(java.util.Date obsdate)
   {
      this.obsdate = obsdate;
   }

   public int getObsvalue()
   {
      return this.obsvalue;
   }

   public void setObsvalue(int obsvalue)
   {
      this.obsvalue = obsvalue;
   }

   public Observation(int userid, java.util.Date obsdate, int obsvalue)
   {
      this.userid = userid;
      this.obsdate = obsdate;
      this.obsvalue = obsvalue;
   }

}