package com.satimetry.nudge;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Participant implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("User ID")
   private int userid;

   @org.kie.api.definition.type.Label(value = "GAS Score")
   private int gasscore;

   public Participant()
   {
   }

   public int getUserid()
   {
      return this.userid;
   }

   public void setUserid(int userid)
   {
      this.userid = userid;
   }

   public int getGasscore()
   {
      return this.gasscore;
   }

   public void setGasscore(int gasscore)
   {
      this.gasscore = gasscore;
   }

   public Participant(int userid, int gasscore)
   {
      this.userid = userid;
      this.gasscore = gasscore;
   }

}